[package]
name = "day"
version = "0.1.0"
authors = ["Anthony Pena <anthony.pena@outlook.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
